"""Schema constants for the repository stock data asset layer."""

SCHEMA_VERSION = 1

DEFAULT_FIELDS = [
    "daily_raw",
    "daily_qfq",
    "features",
    "events",
    "quote",
    "fundamentals",
]

DAILY_RAW_COLUMNS = [
    "trade_date",
    "code",
    "name",
    "open",
    "high",
    "low",
    "close",
    "pre_close",
    "change",
    "change_pct",
    "volume",
    "amount_yuan",
    "turnover_rate_pct",
    "amplitude_pct",
    "limit_up",
    "limit_down",
    "is_limit_up",
    "is_limit_down",
    "is_tradable",
    "is_suspended",
    "is_st",
    "board_type",
    "price_limit_pct",
    "source",
    "fetched_at",
]

DAILY_QFQ_COLUMNS = [
    "trade_date",
    "code",
    "open",
    "high",
    "low",
    "close",
    "volume",
    "amount_yuan",
    "adjustment",
    "source",
    "fetched_at",
]

FEATURE_COLUMNS = [
    "trade_date",
    "code",
    "as_of_date",
    "usable_from",
    "ma5",
    "ma10",
    "ma20",
    "ma30",
    "ma60",
    "ma120",
    "volume_ratio_20d",
    "return_5d",
    "return_10d",
    "return_20d",
    "return_60d",
    "drawdown_20d",
    "drawdown_60d",
    "high_20d",
    "low_20d",
    "high_60d",
    "low_60d",
    "rsi",
    "macd",
    "macd_signal",
    "macd_hist",
    "atr",
    "pe_ttm",
    "pe_static",
    "pb",
    "market_cap_yuan",
    "float_market_cap_yuan",
    "feature_version",
    "generated_at",
]
